import { useState, useEffect, useRef } from 'react'
import { motion } from 'framer-motion'
import { Button } from './ui/button'
import { Input } from './ui/input'
import { Label } from './ui/label'
import Sidebar from './Sidebar'
import TopBar from './TopBar'
import { useSupabase } from '../contexts/SupabaseContext'
import { useAuth } from '../contexts/AuthContext'

function formatCurrency(v) {
  return `$${Number(v || 0).toFixed(2)}`
}

function downloadCSV(filename, rows) {
  if (!rows || rows.length === 0) {
    const blob = new Blob([""], { type: 'text/csv' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = filename
    a.click()
    URL.revokeObjectURL(url)
    return
  }

  const keys = Object.keys(rows[0])
  const csv = [keys.join(',')].concat(rows.map(r => keys.map(k => `"${String(r[k] ?? '')}"`).join(','))).join('\n')
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

export default function ReportsTransactions() {
  const supabase = useSupabase()
  const { user } = useAuth()
  const [fromDate, setFromDate] = useState('')
  const [toDate, setToDate] = useState('')
  const [productId, setProductId] = useState('')
  const [userId, setUserId] = useState('')
  const [products, setProducts] = useState([])
  const [users, setUsers] = useState([])
  const [transactions, setTransactions] = useState([])
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState(null)
  const reportRef = useRef(null)

  useEffect(() => {
    // default last 30 days
    const now = new Date()
    const prior = new Date(now)
    prior.setDate(now.getDate() - 30)
    setToDate(now.toISOString().slice(0, 10))
    setFromDate(prior.toISOString().slice(0, 10))
    // load products and users for filters
    const loadOptions = async () => {
      try {
        const { data: prods } = await supabase.from('products').select('id, name, sku').order('name')
        setProducts(prods || [])
        const { data: usrs } = await supabase.from('users').select('id, full_name, email').order('full_name')
        setUsers(usrs || [])
      } catch (err) {
        console.warn('Failed to load filter options', err)
      }
    }
    loadOptions()
  }, [])

  const loadTransactions = async () => {
    setLoading(true)
    setError(null)
    try {
      let q = supabase
        .from('transactions')
        .select(`id, product_id, quantity_sold, date, total, user_id, products:product_id(name, sku)`)
        .order('date', { ascending: false })

      if (fromDate) q = q.gte('date', fromDate)
      if (toDate) q = q.lte('date', toDate)
      if (productId) q = q.eq('product_id', Number(productId))
      if (userId) q = q.eq('user_id', Number(userId))

      const { data, error } = await q
      if (error) throw error

      // normalize rows for display
      const rows = (data || []).map(tx => ({
        id: tx.id,
        date: tx.date,
        product: tx.products?.name || tx.product_id,
        sku: tx.products?.sku || '',
        quantity_sold: tx.quantity_sold,
        total: Number(tx.total),
        user_id: tx.user_id
      }))

      setTransactions(rows)
    } catch (err) {
      setError(err.message || 'Failed to load transactions')
    } finally {
      setLoading(false)
    }
  }

  const exportCSV = () => {
    const rows = transactions.map(r => ({
      Date: r.date,
      Product: r.product,
      SKU: r.sku,
      Quantity: r.quantity_sold,
      Total: r.total.toFixed(2),
      UserID: r.user_id,
      TransactionID: r.id
    }))
    downloadCSV(`transactions_${fromDate || 'all'}_${toDate || 'all'}.csv`, rows)
  }

  const printReport = () => {
    // open a new window with the report content and call print (user can save to PDF)
    const html = reportRef.current?.innerHTML || '<div>No report</div>'
    const win = window.open('', '_blank', 'noopener,noreferrer')
    if (!win) return
    win.document.write(`
      <html>
        <head>
          <title>Transactions Report</title>
          <style>
            body { font-family: Arial, Helvetica, sans-serif; padding: 20px; }
            table { width: 100%; border-collapse: collapse; }
            th, td { border: 1px solid #ddd; padding: 8px; }
            th { background: #f3f4f6; }
          </style>
        </head>
        <body>
          <h2>Transactions Report</h2>
          <p>Generated by: ${user?.email || 'unknown'}</p>
          <p>Range: ${fromDate || 'all'} — ${toDate || 'all'}</p>
          ${html}
        </body>
      </html>
    `)
    win.document.close()
    win.focus()
    setTimeout(() => win.print(), 500)
  }

  const totalSales = transactions.reduce((s, t) => s + (Number(t.total) || 0), 0)
  const totalItems = transactions.reduce((s, t) => s + (Number(t.quantity_sold) || 0), 0)

  // Simple SalesByDayChart component (inline, no external deps)
  function SalesByDayChart({ transactions }) {
    // aggregate totals per date
    const map = transactions.reduce((acc, tx) => {
      const d = tx.date
      acc[d] = (acc[d] || 0) + Number(tx.total || 0)
      return acc
    }, {})
    const entries = Object.entries(map).sort((a, b) => new Date(a[0]) - new Date(b[0]))
    const max = entries.reduce((m, e) => Math.max(m, e[1]), 0) || 1

    if (entries.length === 0) {
      return <div className="p-4 text-sm text-gray-500">No data to chart</div>
    }

    const width = Math.min(700, Math.max(300, entries.length * 40))
    const height = 120
    const barWidth = Math.max(6, Math.floor(width / entries.length) - 6)

    return (
      <div className="overflow-x-auto">
        <svg width={width} height={height}>
          {entries.map(([date, total], i) => {
            const x = i * (barWidth + 6) + 10
            const h = (Number(total) / max) * (height - 30)
            const y = height - h - 20
            return (
              <g key={date}>
                <rect x={x} y={y} width={barWidth} height={h} fill="#3b82f6" />
                <text x={x + barWidth / 2} y={height - 6} fontSize="10" textAnchor="middle" fill="#374151">{date.slice(5)}</text>
              </g>
            )
          })}
        </svg>
      </div>
    )
  }

  return (
    <div className="flex min-h-screen bg-gradient-to-br from-slate-50 to-slate-100">
      <Sidebar selectedTable="" onTableChange={() => {}} />
      <div className="flex-1 ml-64 p-8">
        <TopBar />

        <motion.div initial={{ opacity: 0, y: -10 }} animate={{ opacity: 1, y: 0 }} className="mb-6 flex items-center justify-between">
          <div>
            <h1 className="text-2xl font-bold">Transactions Report</h1>
            <p className="text-gray-600">Generate and export transaction reports for a date range</p>
          </div>
        </motion.div>

        <div className="bg-white p-4 rounded-lg shadow mb-6 border">
          <div className="flex flex-wrap gap-3 items-end">
            <div className="space-y-1">
              <Label htmlFor="from">From</Label>
              <Input id="from" type="date" value={fromDate} onChange={(e) => setFromDate(e.target.value)} />
            </div>

            <div className="space-y-1">
              <Label htmlFor="to">To</Label>
              <Input id="to" type="date" value={toDate} onChange={(e) => setToDate(e.target.value)} />
            </div>

            <div className="space-y-1">
              <Label htmlFor="product">Product</Label>
              <select id="product" value={productId} onChange={(e) => setProductId(e.target.value)} className="px-3 py-2 border rounded">
                <option value="">All Products</option>
                {products.map(p => (
                  <option key={p.id} value={p.id}>{p.name || p.sku}</option>
                ))}
              </select>
            </div>

            <div className="space-y-1">
              <Label htmlFor="user">User</Label>
              <select id="user" value={userId} onChange={(e) => setUserId(e.target.value)} className="px-3 py-2 border rounded">
                <option value="">All Users</option>
                {users.map(u => (
                  <option key={u.id} value={u.id}>{u.full_name || u.email}</option>
                ))}
              </select>
            </div>

            <div className="ml-auto flex gap-2">
              <Button onClick={loadTransactions} className="gap-2">Load</Button>
              <Button variant="ghost" onClick={() => { setFromDate(''); setToDate(''); setTransactions([]) }}>Reset</Button>
            </div>
          </div>
        </div>

        <div className="mb-4 flex gap-3">
          <div className="bg-white p-4 rounded-lg shadow border flex-1">
            <p className="text-sm text-gray-500">Total Transactions</p>
            <p className="text-xl font-semibold">{transactions.length}</p>
          </div>
          <div className="bg-white p-4 rounded-lg shadow border flex-1">
            <p className="text-sm text-gray-500">Total Items Sold</p>
            <p className="text-xl font-semibold">{totalItems}</p>
          </div>
          <div className="bg-white p-4 rounded-lg shadow border flex-1">
            <p className="text-sm text-gray-500">Total Sales</p>
            <p className="text-xl font-semibold">{formatCurrency(totalSales)}</p>
          </div>
        </div>

        <div className="bg-white p-4 rounded-lg shadow border">
          <div className="flex justify-between items-center mb-4">
            <h2 className="font-semibold">Transactions</h2>
            <div className="flex gap-2">
              <Button onClick={exportCSV}>Export CSV</Button>
              <Button variant="ghost" onClick={printReport}>Print / Save PDF</Button>
            </div>
          </div>

          <div>
            {/* Simple sales-by-day chart */}
            <div className="mb-4">
              <h3 className="font-medium mb-2">Sales by Day</h3>
              <SalesByDayChart transactions={transactions} />
            </div>

            <div ref={reportRef}>
              {loading && <p>Loading…</p>}
              {!loading && error && <p className="text-red-600">{error}</p>}
              {!loading && !error && transactions.length === 0 && (
                <p className="text-gray-600">No transactions found for selected range.</p>
              )}
              {!loading && !error && transactions.length > 0 && (
                <div className="overflow-x-auto">
                  <table className="w-full text-left">
                    <thead>
                      <tr>
                        <th className="p-2">Date</th>
                        <th className="p-2">Product</th>
                        <th className="p-2">SKU</th>
                        <th className="p-2">Quantity</th>
                        <th className="p-2">Total</th>
                        <th className="p-2">User ID</th>
                        <th className="p-2">Transaction ID</th>
                      </tr>
                    </thead>
                    <tbody>
                      {transactions.map(tx => (
                        <tr key={tx.id} className="border-t">
                          <td className="p-2 align-top">{tx.date}</td>
                          <td className="p-2 align-top">{tx.product}</td>
                          <td className="p-2 align-top">{tx.sku}</td>
                          <td className="p-2 align-top">{tx.quantity_sold}</td>
                          <td className="p-2 align-top">{formatCurrency(tx.total)}</td>
                          <td className="p-2 align-top">{tx.user_id}</td>
                          <td className="p-2 align-top">{tx.id}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
